### ISSUE TITLE
New Entity Tracker Bug (at least I have not noticed this one)

### ISSUE THREAD

**Issue by TheProducer835** [codingWithJimmy/LogToSplunk#10]
So player transports via command block from spawn to gardens, bug, then arrives at garden and gets haste.

 CommandBlock at -120,69,259 issued server command: /tp alacercogitatus 69 66 228
[18:03:21 ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_10_R1.ReportedException: Adding entity to track
        at net.minecraft.server.v1_10_R1.EntityTracker.addEntity(EntityTracker.java:141) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.EntityTracker.track(EntityTracker.java:80) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.WorldManager.a(WorldManager.java:19) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.World.b(World.java:1028) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.WorldServer.b(WorldServer.java:1126) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.World.addEntity(World.java:1021) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:514) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:510) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:521) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.MobSpawnerAbstract.c(MobSpawnerAbstract.java:106) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.TileEntityMobSpawner.E_(SourceFile:90) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1496) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:804) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-5391d73-0ebb9c7]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
        at net.minecraft.server.v1_10_R1.EntityTracker.addEntity(EntityTracker.java:108) ~[spigot.jar:git-Spigot-5391d73-0ebb9c7]
        ... 17 more
[18:16:48 INFO]: [@: Given Haste (ID 3) \* 25 to alacercogitatus for 800 seconds]

**Comment by PowerSchill** [comment]
I will have to take a closer look but judging by the message it is not coming from my plugin, at least not directly.
